services:
  php:
    build:
      dockerfile: docker/php/Dockerfile
    volumes:
      - './src:/var/www/html/public'
    container_name: proj-php

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './src:/var/www/html/public'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    depends_on:
      - php
    container_name: proj-nginx

  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'
    container_name: proj-db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 9090:80
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    container_name: proj-phpmyadm
